version: "3"

services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      PBF_URL: https://download.geofabrik.de/europe/italy/centro-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/italy/centro-updates/
      NOMINATIM_PASSWORD: nominatim
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb

volumes:
  nominatim-data:
