version: "3"

services:
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PBF_URL: https://download.geofabrik.de/europe/italy/centro-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/europe/italy/centro-updates/
      NOMINATIM_PASSWORD: nominatim
    volumes:
      - nominatim-data:/var/lib/postgresql/12/main
    shm_size: 1gb
  osrm:
    container_name: osrm
    image: osrm/osrm-backend:latest
    command:
      - sh
      - -c
      - osrm-extract -p /opt/car.lua /data/centro-latest.osm.pbf && osrm-partition /data/centro-latest.osrm && osrm-customize /data/centro-latest.osrm && osrm-routed --algorithm mld /data/centro-latest.osrm
    ports:
      - "5000:5000"
    volumes:
      - osrm_data:/data
      - ./centro-latest.osm.pbf:/data/centro-latest.osm.pbf:ro

volumes:
  nominatim-data:
  osrm_data:
